image: node:16

pipelines:
  branches:
    develop:
      - step:
          name: develop stagging deploy
          caches:
            - node
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_DEV_APP_NAME.git HEAD:master